version: "3.2"
services:
  my_postgres_dev:
    build:
      context: .postgres/.
    image: my_postgres_dev
    depends_on:
      - my_ubuntu_dev
    ports:
      - 5432:5432
  my_ubuntu_dev:
    build:
      context: .ubuntu/.
    image: my_ubuntu_dev 
    ports:
     - "8000:80"
    volumes:
     - "code:/Users/cesarcueva/Documents/projects/personal/Python_Scripting"
    command: tail -F anything